import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../domain/repositories/expense_repository.dart';
import '../state/dashboard/dashboard_cubit.dart';
import '../state/expense_list/expense_list_cubit.dart';
import '../theme/app_theme.dart';
import '../utils/storage_permission_helper.dart';
import 'csv_file_picker_dialog.dart';

class ImportDataDialog extends StatefulWidget {
  final ExpenseRepository repository;

  const ImportDataDialog({
    super.key,
    required this.repository,
  });

  @override
  State<ImportDataDialog> createState() => _ImportDataDialogState();
}

class _ImportDataDialogState extends State<ImportDataDialog> {
  String? _selectedFilePath;
  final TextEditingController _rawCsvController = TextEditingController();
  bool _isImporting = false;
  String? _errorMessage;

  @override
  void dispose() {
    _rawCsvController.dispose();
    super.dispose();
  }

  Future<void> _pickCsvFile() async {
    final hasPermission = await StoragePermissionHelper.requestStoragePermission(
      context,
      showRationale: true,
    );
    if (!hasPermission) return;
    if (!mounted) return;

    final path = await showDialog<String>(
      context: context,
      builder: (_) => const CsvFilePickerDialog(),
    );

    if (path != null && path.isNotEmpty) {
      setState(() {
        _selectedFilePath = path;
        _errorMessage = null;
      });
    }
  }

  Future<void> _importData() async {
    String csvContent = '';

    if (_selectedFilePath != null && _selectedFilePath!.isNotEmpty) {
      final hasPermission = await StoragePermissionHelper.requestStoragePermission(
        context,
        showRationale: true,
      );
      if (!hasPermission) {
        setState(() {
          _errorMessage = 'Storage permission is required to read CSV file.';
        });
        return;
      }

      try {
        final file = File(_selectedFilePath!);
        if (await file.exists()) {
          csvContent = await file.readAsString();
        } else {
          setState(() {
            _errorMessage = 'Invalid CSV, please upload CSV file Generated by MoneyMan app.';
          });
          return;
        }
      } catch (e) {
        setState(() {
          _errorMessage = 'Invalid CSV, please upload CSV file Generated by MoneyMan app.';
        });
        return;
      }
    } else {
      csvContent = _rawCsvController.text.trim();
    }

    if (csvContent.isEmpty) {
      setState(() {
        _errorMessage = 'Please select a MoneyMan .csv file or paste valid CSV content.';
      });
      return;
    }

    if (!mounted) return;

    // Alert user before importing
    final confirm = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppTheme.cardBackgroundColor,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Text(
          'Warning: Data Overwrite',
          style: TextStyle(color: AppTheme.expenseColor, fontWeight: FontWeight.bold),
        ),
        content: const Text(
          "All existing app data will be deleted. Export it if you don't want to loose it.",
          style: TextStyle(color: AppTheme.textColor, fontSize: 14),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Cancel', style: TextStyle(color: AppTheme.textColor)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppTheme.expenseColor,
              foregroundColor: AppTheme.textColor,
            ),
            onPressed: () => Navigator.pop(ctx, true),
            child: const Text('Import'),
          ),
        ],
      ),
    );

    if (confirm != true) {
      return;
    }

    setState(() {
      _isImporting = true;
      _errorMessage = null;
    });

    try {
      final count = await widget.repository.importFromCsv(csvContent);

      if (mounted) {
        context.read<DashboardCubit>().loadDashboard();
        context.read<ExpenseListCubit>().loadExpenses();

        Navigator.pop(context, true);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Successfully loaded $count records from CSV', style: const TextStyle(color: AppTheme.textColor)),
            backgroundColor: AppTheme.cardBackgroundColor,
            duration: const Duration(seconds: 4),
          ),
        );
      }
    } catch (e) {
      setState(() {
        if (e is FormatException) {
          _errorMessage = e.message;
        } else {
          _errorMessage = 'Invalid CSV, please upload CSV file Generated by MoneyMan app.';
        }
        _isImporting = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: AppTheme.cardBackgroundColor,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Row(
                  children: [
                    Icon(Icons.file_download_rounded, color: AppTheme.baseHighlightColor, size: 28),
                    SizedBox(width: 10),
                    Text(
                      'Import CSV Data',
                      style: TextStyle(
                        color: AppTheme.textColor,
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
                IconButton(
                  icon: const Icon(Icons.close_rounded, color: AppTheme.textColor),
                  onPressed: () => Navigator.pop(context),
                ),
              ],
            ),
            const SizedBox(height: 16),

            const Text(
              'Select MoneyMan Exported .csv File',
              style: TextStyle(color: AppTheme.textColor, fontSize: 13, fontWeight: FontWeight.w600),
            ),
            const SizedBox(height: 8),

            // File Selector Box
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: AppTheme.backgroundColor,
                borderRadius: BorderRadius.circular(14),
                border: Border.all(color: AppTheme.textColor.withValues(alpha: 0.3)),
              ),
              child: Row(
                children: [
                  const Icon(Icons.description_rounded, color: AppTheme.baseHighlightColor, size: 24),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Selected CSV File',
                          style: TextStyle(color: AppTheme.textColor, fontSize: 12, fontWeight: FontWeight.bold),
                        ),
                        Text(
                          _selectedFilePath ?? 'No file selected',
                          style: TextStyle(
                            color: _selectedFilePath != null ? AppTheme.baseHighlightColor : AppTheme.textColor.withValues(alpha: 0.6),
                            fontSize: 11,
                            fontFamily: 'monospace',
                          ),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ],
                    ),
                  ),
                  ElevatedButton.icon(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppTheme.baseHighlightColor,
                      foregroundColor: AppTheme.backgroundColor,
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    ),
                    icon: const Icon(Icons.folder_open_rounded, size: 16),
                    label: const Text('Browse', style: TextStyle(fontSize: 12)),
                    onPressed: _pickCsvFile,
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),

            // Error Alert Banner
            if (_errorMessage != null) ...[
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: AppTheme.expenseColor.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: AppTheme.expenseColor),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.warning_amber_rounded, color: AppTheme.expenseColor, size: 22),
                    const SizedBox(width: 10),
                    Expanded(
                      child: Text(
                        _errorMessage!,
                        style: const TextStyle(color: AppTheme.textColor, fontSize: 12, fontWeight: FontWeight.bold),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
            ],

            // Raw CSV Text Accordion Option
            ExpansionTile(
              tilePadding: EdgeInsets.zero,
              collapsedIconColor: AppTheme.textColor,
              iconColor: AppTheme.baseHighlightColor,
              title: const Text(
                'Or Paste Raw CSV Content',
                style: TextStyle(color: AppTheme.textColor, fontSize: 13, fontWeight: FontWeight.w600),
              ),
              children: [
                TextField(
                  controller: _rawCsvController,
                  maxLines: 5,
                  style: const TextStyle(fontFamily: 'monospace', fontSize: 11, color: AppTheme.textColor),
                  decoration: const InputDecoration(
                    hintText: 'Paste CSV rows here...',
                  ),
                ),
              ],
            ),
            const SizedBox(height: 24),

            // Primary Import Button
            SizedBox(
              width: double.infinity,
              height: 50,
              child: ElevatedButton.icon(
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.baseHighlightColor,
                  foregroundColor: AppTheme.backgroundColor,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                ),
                icon: const Icon(Icons.download_rounded, color: AppTheme.backgroundColor),
                label: _isImporting
                    ? const CircularProgressIndicator(color: AppTheme.backgroundColor)
                    : const Text(
                        'Import & Load Data',
                        style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                      ),
                onPressed: _isImporting ? null : _importData,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
